### ISSUE TITLE
styles/_classes.scss:3 has a CORS problem

### ISSUE THREAD

**Issue by kyan001** [hibiyasleep/ikegami#25] opened 2020-07-21 17:07 UTC
it is the "FFXIVAppIcons.woff" file. What I try is downloaded it and put it under project folder, change the url to 
```
src: url('/FFXIVAppIcons.woff') format('woff');
```
and it works, but I don't know where should I put the woff file.

BTW, githack,com is blocked in some country.

**Comment by hibiyasleep** [comment] 2020-08-18 19:34
I was totally dumb, I made 84589570ce188b330d8c897d69007476a6b36528 (newer one) as duplicate of 2f197a45c29ee745a59edbebb435b2c48b53fb3d (old dirty-testing one, shouldn't been there). anyway, it's fixed on 84589570ce188b330d8c897d69007476a6b36528. sorry :sob:

**Closed by hibiyasleep** 2020-08-18 19:34 UTC
